language: java

jdk:
- oraclejdk8

branches:
  only:
  - master

env:
  global:
  - secure: oMOfwU+VhMWDogGVRZORA5jnJn2fwUUyTJNA6IYfIBdQJ11FnpiINNSq3+SXxu9+R+cJHogm4pypPpNKKbyKHJBqHIjJ3tZ5PZpIaqKykWihpX2AgJkp2z6IGR5UFkCdh/zgYUpVCHc133TyZ7vBj4z92mEiK3eNUu4yV03B1RuIuIgcyJqhChArU+1SbZ1j52l3kZviZtVnLFOZ9w8zOYJ8e/odvACIJuU353nBe/wOK4yHP3jad/q4lb0BZxad83gIRaRnL7WssoRW0iMu39mpkgo6wlsGWR8T29o6i9WPzUX2T3G/DFL7G4krKB/UJ1IO5ji2ywsf4Hk7fmsYjB6SqE9e74Frg7KnRQ/WERP1TUL34u2FA1Gzb4ahQlhR/Yrb8MEnD/AQsd7m/YoQYdTuYxI2D0EdlkqqAQEAjMgEbCGBomiG/7C/pB/VFPmXrpYnS+mTGowOsZhdyoIYArBgQCt+8l9wLGPfmMig5gRK0GcsCxkeMJulZaiZfb5O0r/CBkRaGuRfzF1jiHXVEBuYcU1mbM8y3thwF08iAtFX5t0zs6LGDDQZRrIOSa1efilHsoBmJ4Jjd8uYgpu+bov7Ngjgw6qzpA8pA/IFeZJr9P9NxpaRcWpneIkY9OE3XBT6cz3AtfxD60+Bd74LB2XG+co4ytT7AKhYgaV8qDc=

script: ./gradlew clean build jacocoTestReport

after_success:
- ./gradlew check jacocoTestReport coveralls

after_failure:
- ./gradlew clean check --debug

notifications:
  slack:
    secure: eDiClIlOjyF6VuaQL3xu2uVhtjWL2Ve8pTAVb99z50k/HoIXCUyQY1w+dGbiR+LOVxP4g81nH6nDHJA5i9mmj+hqiQK/2CEKP1w7ZndUP53DFXK3nGyDsxoRCweLMnd9Y5mtqwJ3BGb6RsndC42wcbhzJ8/d0LCHpCq8UtmMMIKSNjotrZrysTcgehgGZ1xligveYAInYuyAZInCfQiVWDPWJ1msiI0Vx2Sr2YQNTMCz4UHMOzpfa75UERo61Z3FxLQjBWEpBq6AYgKRtJbqsoOPXctDZbcTmdb6x7UL1BxgGRQF9EL6jixxCcSK9qJpUTma/UN49L9Lst9kjDYP7/Ymffrl3NDBMJQt0cSVcpsKw0p2mXEhITQX+oo1DL6vfhzGCRKe9qylun42MdxJMCvqOHHkY9UkUn4nLteINFsZFCmV4l/Wu46dYLsivXIldsSdPrWQ/MxzIFAJtehnkQtJvs0qe0ogZ99jGLHxQRVHWx5imVMpZFxzaQu+aCeONxmF8aR0ynUxkfupPTcA/HDGkL6HC6gpKDWjvhlPJwMGTa1oDfcACfLx6Qxv0XBPKzhKc8ayBxxDvqvPXF22udHsv3b22VriwoFHqIbJFYAxR3oDdFj44K1DnEHaNhOLBX45YL4aKa8Wtjl0gFimy7jnNcVPRVjfhigCU+niOhg=
